// hellman-app_react/src/components/core/gridview/simple-gridview/simple-gridview.tsx
import React, { useEffect } from 'react';
import TableSettings,{TableHeader} from '../TableSettings';

import PaginationService from '../../pagination/PaginationService';
import PaginationSettings from '../../pagination/PaginationSettings';
import Pagination from '../../pagination/Pagination';

interface SimpleGridviewProps {
    id: string;
    type: string;
    actionPosition: string;
    pagination?: boolean;
    perPage?: number;
    settings: TableSettings;
}

const SimpleGridview: React.FC<SimpleGridviewProps> = ({
    id,
    type,
    actionPosition,
    pagination,
    perPage,
    settings
  }) => {
  
    const [page, setPage] = React.useState(1);
    const [gridSettings, setGridSettings] = React.useState(settings);
    const [total, setTotal] = React.useState(0);
    const [count, setCount] = React.useState(0);


    function renderHeader(header: TableHeader){
        let title = header.columnTitle;
        if(header.align == "center"){
            return (<th key={title} style={{ textAlign: "center"}}>{header.columnTitle}</th>)
        }
        else if(header.align == "right"){
            return (<th key={title} style={{ textAlign: "right"}}>{header.columnTitle}</th>)
        }
        else if(header.align == "left"){
            return (<th key={title} style={{ textAlign: "left"}}>{header.columnTitle}</th>)
        }else{
            return (<th key={title} style={{ textAlign: "left"}}>{header.columnTitle}</th>)
        }
    }

    function renderRow(dt: any, index: number){
        let headers: Array<TableHeader> = settings.headers;
        let key = headers.find(x=>x.key);
        if(key){
            return (
                <tr key={dt[key.columnName]}  className={""+showLine(index)}>
                {
                    settings.headers.map(function (header : TableHeader) {
                        return renderCell(dt,header);
                    })
                }
                </tr>
            )
        }
    }

    function renderCell(dt: any, header: TableHeader){
        if(dt.editting){
            return (
             <td>
                 <input 
                    disabled = {header.disabled}
                    name={header.columnName}
                    className="form-control"/>
             </td>)
         }else{
             return (<td><span>{dt[header.columnName]}</span></td>)
         }
    }

    function changePage(current: number ){
         setPage(current);
    }


    function showLine(index: number){
        if(perPage !== undefined){
            let min = index >= (page-1)*perPage;
            let max = index < page * perPage;
            return !(min && max)?"hidden":"";
        }
      }


    useEffect(() => {
        setGridSettings(settings);
        setTotal(settings.data.length)
    },[settings,total,page]);



    return (
       <div>
            <table id={id} className="table">
                <thead>
                    <tr>
                        {settings.headers.map(renderHeader)}
                    </tr>
                </thead>
                <tbody>
                       {settings.data.map((current: any, index: number) => {
                            return renderRow(current,index);
                       })}
                </tbody>
            </table>
           <Pagination 
              page={page}
              perPage={perPage?perPage:5}  
              totalRecords={total}
              changePage={changePage}
            />
           
       </div>
    );
  };
  
  export default SimpleGridview;

// hellman-app_angular/src/app/core/gridview/simple-gridview/simple-gridview.component.ts
import { Component, OnInit, Input, OnChanges } from '@angular/core';
import TableSettings, { TableHeader, GridviewType, ActionPosition } from '../table-settings';
import PaginationSettings from '../../pagination/pagination';

import GrdiviewCoreComponent from '../gridview-core-component';

import { PaginationService } from '../../pagination/pagination.service';

@Component({
  selector: 'app-simple-gridview',
  templateUrl: './simple-gridview.component.html',
  styleUrls: ['./simple-gridview.component.css']
})
export class SimpleGridviewComponent extends GrdiviewCoreComponent  implements OnInit,OnChanges {

  @Input() settings: TableSettings;

  pageSettings : PaginationSettings;

  constructor( public paginationService: PaginationService) {
    super();
  }

  ngOnInit() {
    this.configuration();
  }

  ngOnChanges(changes: import("@angular/core").SimpleChanges): void {
     this.configuration();
  }

  configuration(){
    setTimeout(() => {
         this.setPaginationInfo();
     },100);
  }

  setPaginationInfo(){
    if(this.settings.pagination){
        let perPage = this.settings.perPage !== null? this.settings.perPage:0;
        if(this.settings.data){
          if(this.settings.data.length > 0){
            this.totalRecords = this.settings.data.length;
            this.pageSettings = this.paginationService.setPageSettings(1,perPage,this.totalRecords);
          }
        }
     }
  }
  saveInline(formInline: any, action: string) {
  
  }

  deleteInline(formInline: any) {

  }


}

<form #f="ngForm" >
        <table class="table">
          <thead>
            <tr>
                <th [style.textAlign]="header.align" *ngFor="let header of settings.headers" scope="col">{{header.columnTitle}}</th>
            </tr>
          </thead>
          <tbody>
              
               <tr [hidden]="showLine(i)"  *ngFor="let dt of settings.data;let i = index">
                  <td  [style.textAlign]="header.align" *ngFor="let header of settings.headers">
                      <span *ngIf="!dt.editting">{{ dt[header.columnName]}} </span>
                      <input *ngIf="dt.editting"
                              [ngModel]="dt[header.columnName]" 
                              [disabled] = "header.disabled"
                              class="form-control"
                              [name]="header.columnName"> 
                  </td>
               </tr>
          </tbody>
        </table>
      </form>
      <app-pagination 
         [settings]="pageSettings" 
         (pageChange) = "changePage($event)"
         *ngIf="settings.pagination">
      </app-pagination>
