// hellman-app_angular/src/app/core/pagination/pagination.component.ts
import { Component, OnInit, Input, OnChanges, Output, EventEmitter } from '@angular/core';
import PaginationSettings, { Page } from './pagination';
import { PaginationService } from './pagination.service';

@Component({
  selector: 'app-pagination',
  templateUrl: './pagination.component.html',
  styleUrls: ['./pagination.component.css']
})
export class PaginationComponent implements OnInit,OnChanges {
 
  page : number=1;
  pages : Array<Page> = new Array<Page>();
  pageShow : number = 6;
  @Input() settings : PaginationSettings;
  @Output() pageChange = new EventEmitter<number>();
  
  constructor(public paginationService : PaginationService) { }

  ngOnInit() {
  }

  ngOnChanges(changes: import("@angular/core").SimpleChanges): void {
    setTimeout(() => {
      this.setPageSettings();
    },100);

  }

  onPage(page : number){
    this.page = page;
    this.setPageSettings();
  }

  onNext(page : number){
    this.page = ++page;
    this.setPageSettings();
  }

  onPrevious(page : number){
    this.page = --page;
    this.setPageSettings();
  }


  setPageSettings(){
    if(this.settings){
        let aux = this.settings.totalRecords%this.settings.perPage;
        let countPages = Math.floor(this.settings.totalRecords/this.settings.perPage);
        if(aux !== 0)
        {
          countPages +=1;
        }
        
        if(countPages == 1){
          this.page = 1;
        }
        this.showPages(countPages);
        this.pageChange.emit(this.page);
     }
  }
  
  showPages(countPages: number)
  {
      this.pages = [];
      let count = 1;
      for(let i = 0;i < countPages;i++){
          let show = false;
          if(count < this.page + this.pageShow)
          {
             show= true;
          }
          this.pages.push(new Page(count, show));
          count++;
      }
  }

  activePage(page : any)
  {
    
    let active: boolean = false;
    if(page == this.page){
      active = true;
    }
    return {
      'active': active
    }
  }

  disabledPage(page : number, type: string)
  {
    
    let disabled: boolean = false;
    if(page == 1 && type == "P"){
      disabled = true;
    }else if(page == this.pages.length && type == "N"){
      disabled = true;
    }
    return {
      'disabled': disabled
    }
  }

  
}

  <nav aria-label="PageGridview">
    <ul class="pagination">
      <li [ngClass]="disabledPage(page,'P')" class="page-item">
        <a (click)="onPrevious(page)" class="page-link">Previous</a>
      </li>
      <li  [ngClass]="activePage(p.value)"  [hidden]="!p.visible" *ngFor="let p of pages" class="page-item">
          <a (click)="onPage(p.value);" class="page-link">{{p.value}}</a>
      </li>
      <li [ngClass]="disabledPage(page,'N')"  class="page-item">
        <a  (click)="onNext(page)" class="page-link">Next</a></li>
    </ul>
  </nav>

// hellman-app_react/src/components/core/pagination/Pagination.tsx
import React, { useEffect } from 'react';
import PaginationSettings, { Page } from './PaginationSettings';
interface PaginationProps{
    page?: number;
    perPage: number;
    totalRecords : number;
    changePage: Function;
}
const Pagination: React.FC<PaginationProps> = ({ 
    page,
    perPage,
    totalRecords,
    changePage
 }) => {
    
    const [currentPage, setCurrentPage] = React.useState(1);
    const [pages, setPages] = React.useState(new Array<Page>());
    const [pageShow, setPageShow] = React.useState(6);
    const [total, setTotal] = React.useState(totalRecords);
    const [paginationSettings, setPaginationSettings] = React.useState(
        new PaginationSettings(page?page:1,perPage,totalRecords)
    );

    useEffect(() => {
        setTotal(totalRecords);
        setPageSettings(1);
    },[totalRecords]);


    function onPage(page : number){
        setCurrentPage(page);
        setPageSettings(page);
    }

    function onNext(page : number){
        setCurrentPage(++page);
        setPageSettings(++page);
    }

    function onPrevious(page : number){
        setCurrentPage(--page);
        setPageSettings(--page);
    }

    function setPageSettings(page: number){
        let aux = totalRecords%perPage;
        let countPages = Math.floor(totalRecords/perPage);
        if(aux !== 0)
        {
            countPages +=1;
        }
        showPages(countPages);
        changePage(page);
    }

    function showPages(countPages: number){
        let pages = [];
        let count = 1;
        for(let i = 0;i < countPages;i++){
            let show = false;
            if(count < currentPage + pageShow)
            {
                show= true;
            }
            pages.push(new Page(count, show));
            count++;
        }
        setPages(pages);
    }

    function activePage(pag: any)
    {
        let active: boolean = false;
        if(pag == currentPage){
            active = true;
        }

        return active?"active":"";
    }

    function visible(page: Page){
        
       return !page.visible?"hidden":"";
    }

    function disabledPage(page : number, type: string)
    {
      
      let disabled: boolean = false;
      if(page == 1 && type == "P"){
         disabled = true;
      }
      else if(page == pages.length && type == "N"){
         disabled = true;
      }

      return disabled?"disabled":"";
    }

    function renderPage(p: Page){
         return  (
              <li  className={"page-item "+ activePage(p.value) + " " + visible(p)}>
                  <a onClick={() => onPage(p.value)}  className="page-link">
                     {p.value}
                  </a>
              </li>
         );
    }

    return (
      <nav aria-label="PageGridview">
            <ul className="pagination">
                    <li className={"page-item "+ disabledPage(currentPage,"P")}>
                         <a  onClick={() => onPrevious(currentPage)} className="page-link">Previous</a>
                    </li>
                    {
                        pages.map(renderPage)
                    }
                   <li className={"page-item "+ disabledPage(currentPage,"N")}>
                         <a  onClick={() => onNext(currentPage)} className="page-link">Next</a>
                    </li>
            </ul>
      </nav>
    );
};

export default Pagination;
