// hellman-app_react/src/components/core/gridview/gridview-in-memory/gridview-in-memory.tsx
import React, { useEffect } from 'react';
import TableSettings,{TableHeader,ActionPosition} from '../TableSettings';

import PaginationService from '../../pagination/PaginationService';
import PaginationSettings from '../../pagination/PaginationSettings';
import Pagination from '../../pagination/Pagination';

interface GridviewProps {
    id: string;
    type: string;
    actionPosition: string;
    pagination?: boolean;
    perPage?: number;
    settings: TableSettings;
}

export enum Action {
    Insert = 1,
    Edit = 2,
    Delete = 3,
}

const GridviewInMemory: React.FC<GridviewProps> = ({
    id,
    type,
    actionPosition,
    pagination,
    perPage,
    settings
  }) => {
  
    const [page, setPage] = React.useState(1);
    const [gridSettings, setGridSettings] = React.useState(settings);
    const [total, setTotal] = React.useState(0);
    const [editting, setEditting] = React.useState(false);
    const [row, setRow] = React.useState(settings.data[0]);

    function renderHeader(header: TableHeader){
        let title = header.columnTitle;
        let th = null;
        if(header.align == "center"){
            th = (<th key={title} style={{ textAlign: "center"}}>{header.columnTitle}</th>)
        }
        else if(header.align == "right"){
            th = (<th key={title} style={{ textAlign: "right"}}>{header.columnTitle}</th>)
        }
        else if(header.align == "left"){
            th =  (<th key={title} style={{ textAlign: "left"}}>{header.columnTitle}</th>)
        }else{
            th  = (<th key={title} style={{ textAlign: "left"}}>{header.columnTitle}</th>)
        }
        return th;
    }

    function renderHeaderAction(type : ActionPosition){
        let position : ActionPosition = actionPosition.toLowerCase() === "left"
          ? ActionPosition.Left: ActionPosition.Right;
          if( position == type){
              return(
                <th className="ctr actions" scope="col">
                    <a onClick={() => insertRow()}>
                        <i className="fa fa-plus"></i>
                    </a>
                 </th>
              )
          }
    }


    function renderInsertRow(){
        if(editting){
            return(
                <tr>
                    {renderSaveAction(ActionPosition.Left)}
                    {settings.headers.map(renderInsert)}
                    {renderSaveAction(ActionPosition.Right)}
                 </tr>
            );
        }
    }

    function renderInsert(header: TableHeader){
        return (
            <td>
                <input 
                   disabled = {header.disabled}
                   defaultValue={row[header.columnName]}
                   onChange={($event) => changeRow(header.columnName,$event.target)}
                   name={header.columnName}
                   className="form-control"/>
            </td>
        )
    }

    function renderSaveAction(type : ActionPosition){
        let position : ActionPosition = actionPosition.toLowerCase() === "left"
           ? ActionPosition.Left: ActionPosition.Right;
        if( position == type){
            return (
                <td className="ctr actions">
                    <a><i onClick={() => saveInline(Action.Insert,-1)} className="fa fa-save"></i></a>
                    <a><i onClick={() => cancelInsert()} className="fa fa-ban"></i></a>
                </td>
            )
        }
    }
    /*--------- rows ------------*/
    function renderRow(dt: any, index: number){
        let headers: Array<TableHeader> = settings.headers;
        let key = headers.find(x=>x.key);
        let cells = null;
        if(key){
            return (
                <tr key={dt[key.columnName]}  className={""+showLine(index)}>
                 {
                      cells =  renderAction(ActionPosition.Left, dt, index)
                 }
                 {
                    settings.headers.map(function (header : TableHeader) {
                       cells = renderCell(dt,header);
                       return cells;
                    })
                }
                {
                      cells =  renderAction(ActionPosition.Right, dt,index)
                }
                </tr>
            )
        }
    }
    
    function renderAction(type : ActionPosition, row: any, index: number){
        let position : ActionPosition = actionPosition.toLowerCase() === "left"
           ? ActionPosition.Left: ActionPosition.Right;
        if( position == type){
            if(!row.editting){
                return (
                    <td className="ctr actions">
                        <a><i onClick={() => editRow(row,index)} className="fa fa-pencil"></i></a>
                        <a><i onClick={() => deleteInline(row,index)} className="fa fa-trash"></i></a>
                    </td>
                )
            }else{
                return (
                    <td className="ctr actions">
                        <a><i onClick={() => saveInline(Action.Edit, index)} className="fa fa-save"></i></a>
                        <a><i onClick={() => cancelEdit(row,index)}  className="fa fa-ban"></i></a>
                    </td>
                )
            }
         
        }
    }

    function renderCell(dt: any, header: TableHeader){
        if(dt.editting){
            return (
             <td>
                 <input 
                    disabled = {header.disabled}
                    name={header.columnName}
                    defaultValue={row[header.columnName]}
                    onChange={($event) => changeRow(header.columnName,$event.target)}
                    className="form-control"/>
             </td>)
         }else{
             return (<td><span>{dt[header.columnName]}</span></td>)
         }
    }

    function changePage(current: number ){
         setPage(current);
    }


    function showLine(index: number){
        if(perPage !== undefined){
            let min = index >= (page-1)*perPage;
            let max = index < page * perPage;
            return !(min && max)?"hidden":"";
        }
    }

    function insertRow(){
        setEditting(true);
        clearRow();
    }

    function clearRow(){
        var row:any = {};
        settings.headers.forEach(header => {
            row[header.columnName] = "";
        });
        setRow(row);
    }

    function cancelInsert(){
        setEditting(false);
    }


    function editRow(row: any, index: number){
        row.editting = true;
        let data = gridSettings.data;
        data.splice(index,1,row)
        setRow(row);
        setGridSettings({...gridSettings, data: data});
    }

    function cancelEdit(row: any, index: number){
        row.editting = false;
        changeData(row, index);
       
    }

    function changeData(row: any, index: number){
        let data = gridSettings.data;
        data.splice(index,1,row);
        setGridSettings({...gridSettings, data: data});
    }

    const changeRow = (field:any,element: any) => {
        let rw = row;
        rw[field] = element.value;
        setRow(rw);
    };

    function saveInline(action: Action, index: number){
        let data = gridSettings.data;
        if(action == Action.Insert){
            let key = gridSettings.headers.find(x=>x.key);
            if(key){
                row[key.columnName] = data.length+1;
            }
            data.push(row);
            cancelInsert();
        }
        else if(action == Action.Edit){
            cancelEdit(row,index);
        }
        setGridSettings({...gridSettings, data: data});
        clearRow();
    }
    
    function deleteInline(row: any,index: number){
        let data = gridSettings.data;
        data.splice(index,1);
        setGridSettings({...gridSettings, data: data});
    }
 

    useEffect(() => {
        setGridSettings(settings);
        setTotal(settings.data.length)
    },[settings,total,page]);



    return (
       <div>
            <table id={id} className="table">
                <thead>
                    <tr>
                        {renderHeaderAction(ActionPosition.Left)}
                        {gridSettings.headers.map(renderHeader)}
                        {renderHeaderAction(ActionPosition.Right)}
                    </tr>
                </thead>
                <tbody>
                       {renderInsertRow()}
                       {gridSettings.data.map((current: any, index: number) => {
                            return renderRow(current,index);
                       })}
                </tbody>
            </table>
           <Pagination 
              page={page}
              perPage={perPage?perPage:5}  
              totalRecords={total}
              changePage={changePage}
            />
           
       </div>
    );
  };
  
  export default GridviewInMemory;

// hellman-app_angular/src/app/core/gridview/gridview-in-memory/gridview-in-memory.component.ts
import { Component, OnInit, Input, OnChanges, ComponentFactoryResolver } from '@angular/core';
import { BsModalService, BsModalRef } from 'ngx-bootstrap/modal';
import { Subscription } from 'rxjs';
import { take } from 'rxjs/internal/operators/take';

import GrdiviewCoreComponent from '../gridview-core-component';

import TableSettings, { TableHeader, GridviewType, ActionPosition } from '../table-settings';
import PaginationSettings from '../../pagination/pagination';

import AlertService from '../../alert/alert.service';
import ConfirmService from '../../confirm/confirm.service';
import { PaginationService } from '../../pagination/pagination.service';

@Component({
  selector: 'app-gridview-in-memory',
  templateUrl: './gridview-in-memory.component.html',
  styleUrls: ['./gridview-in-memory.component.css']
})
export class GridviewInMemoryComponent extends GrdiviewCoreComponent implements OnInit {

  
  @Input() settings: TableSettings;

  pageSettings : PaginationSettings;
  newData : any;
  page: number = 1;
  deleteModalRef: BsModalRef;
  counter: number = 0;

  subscription: Subscription;
  
  constructor( 
    private alertService : AlertService,
    private confirmService: ConfirmService,
    public paginationService: PaginationService
    ) { 
    super();
  }

  ngOnInit() {
    this.configuration();
  }

  ngOnChanges(changes: import("@angular/core").SimpleChanges): void {
     this.configuration();
  }

  configuration(){
    setTimeout(() => {
       this.onRefrech();
     },100);
  }

  onRefrech(){
    this.newData = { ...this.settings.data[0]}; 
    this.loadNew();
    this.setPaginationInfo();
  }

  loadNew(){
     this.counter = this.settings.data.length+1; 
     this.settings.headers.forEach(header => {
        let value :any = "";
        if(header.key)
          value = this.counter;
          this.newData[header.columnName] = value;
      });
  }

  setPaginationInfo(){
    if(this.settings.pagination){
        let perPage = this.settings.perPage !== null? this.settings.perPage:0;
        if(this.settings.data){
          if(this.settings.data.length > 0){
            this.totalRecords = this.settings.data.length;
            this.pageSettings = this.paginationService.setPageSettings(1,perPage,this.totalRecords);
          }
        }
     }
  }

  saveInline(formInline: any, dt: any) {
    let message : string  = "Registro atualizado com sucesso!";
    if(!dt){
      this.cancelInsertInline();
      message = "Registro inserido com sucesso!";
      this.settings.data.push(formInline.value);
      this.onRefrech();
    }
    else{
      this.cancelEditInline(dt);
      this.editRow(formInline.value);
    }
    this.alertService.showSuccess(message);
  }

  findIndex(dt: any)
  {
    let headerKey = this.settings.headers.find(x=>x.key);
    let filter : any = dt[headerKey.columnName];
    let index: number = this.settings.data.findIndex(x=>x[headerKey.columnName] === filter);
    return index;
  }

  findElement(dt: any)
  {
    let headerKey = this.settings.headers.find(x=>x.key);
    let filter : any = dt[headerKey.columnName];
    let index: number = this.settings.data.findIndex(x=>x[headerKey.columnName] === filter);
    return this.settings.data.find(x=>x[headerKey.columnName] === filter);
  }
 
  editRow(dt: any){
     let index = this.findIndex(dt);
     this.settings.data.splice(index,1,dt);
  }

  deleteInline(formInline: any) {
    const confirmObservable = this.confirmService.showConfirm('Confirmacao', 'Tem certeza que deseja remover esse curso?');
    confirmObservable.asObservable().pipe(take(1)).subscribe(result => this.onDelete(result,formInline) );    
  }



  onDelete(result :boolean, data: any)
  {
      if(result)
      {
          this.deleteRow(data);
          this.alertService.showSuccess("Registro deletado com sucesso!");
      }
  }

  deleteRow(dt: any){
    let index = this.findIndex(dt);
    this.settings.data.splice(index,1);
  }

}

  
<form #f="ngForm" >
        <table class="table">
          <thead>
            <tr>
                <th class="ctr actions" *ngIf="settings.actionPosition == 1" scope="col"><a (click)="insertInline()"><i class="fa fa-plus"></i></a></th>
                <th [style.textAlign]="header.align" *ngFor="let header of settings.headers" scope="col">{{header.columnTitle}}</th>
                <th class="ctr actions" *ngIf="settings.actionPosition == 2" scope="col"><a (click)="insertInline()"><i class="fa fa-plus"></i></a></th>
            </tr>
          </thead>
          <tbody>
              <tr *ngIf="editting">
                  <td class="ctr actions"  *ngIf="settings.actionPosition == 1"> 
                      <a (click)="saveInline(f)"><i class="fa fa-save"></i></a>
                      <a (click)="cancelInsertInline()"><i class="fa fa-ban"></i></a>
                  </td>
                  <td *ngFor="let header of settings.headers">
                      <input [ngModel]="newData[header.columnName]" 
                             [readonly] = "header.disabled"
                             [name]="header.columnName"
                             class="form-control" 
                             value=""> 
                  </td>
                  <td class="ctr actions"  *ngIf="settings.actionPosition == 2"> 
                      <a (click)="saveInline(f)"><i class="fa fa-save"></i></a>
                      <a (click)="cancelInsertInline()"><i class="fa fa-ban"></i></a>
                  </td>
               </tr>
               <tr [hidden]="showLine(i)"  *ngFor="let dt of settings.data;let i = index">
                  <td class="ctr actions"  *ngIf="settings.actionPosition == 1"> 
                      <div *ngIf="!dt.editting">
                          <a  (click)="editInline(dt);formData = dt"><i class="fa fa-pencil"></i></a>
                          <a><i (click)="deleteInline(dt)" class="fa fa-times"></i></a>
                      </div>
                      <div *ngIf="dt.editting">
                        <a (click)="saveInline(f,dt)"><i class="fa fa-save"></i></a>
                        <a (click)="cancelEditInline(dt)"><i class="fa fa-ban"></i></a>
                      </div>
                  </td>
                  <td  [style.textAlign]="header.align" *ngFor="let header of settings.headers">
                      <span *ngIf="!dt.editting">{{ dt[header.columnName]}} </span>
                      <input *ngIf="dt.editting"
                              [ngModel]="dt[header.columnName]" 
                              [readonly] = "header.disabled"
                              class="form-control"
                              [name]="header.columnName"> 
                  </td>
                  <td class="ctr actions"  *ngIf="settings.actionPosition == 2"> 
                      <div *ngIf="!dt.editting">
                          <a  (click)="editInline(dt);formData = dt"><i class="fa fa-pencil"></i></a>
                          <a><i (click)="deleteInline(dt)" class="fa fa-times"></i></a>
                      </div>
                      <div *ngIf="dt.editting">
                        <a (click)="saveInline(f,dt);"><i class="fa fa-save"></i></a>
                        <a (click)="cancelEditInline(dt)"><i class="fa fa-ban"></i></a>
                      </div>
                  </td>
               </tr>
          </tbody>
        </table>
      </form>
      <app-pagination 
         [settings]="pageSettings" 
         (pageChange) = "changePage($event)"
         *ngIf="settings.pagination">
      </app-pagination>
